@startuml energy_hub_container
!include ../C4_Container.puml

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()

title EcoStruxure Microgrid Advisor

Person(customer, Users, "ema 用户")

System_Boundary(emaSystem, "Ema Context") {
    Container(emaUI, "EmaUI", "ema前端服务")
    Container(ema, "Ema", "ema后端服务")
    Container(AuthUI, "AuthUI", "ema权限管理前端服务")
    Container(userAuth, "UserAuth", "ema权限管理后端服务")
    Container(veeUi, "VeeUi", "数据质量管理UI")
    Container(emaGateway, "EmaGateway", "ema 网关服务")

    Rel_D(emaUI,emaGateway,"call", "JSON/HTTP")
    Rel_D(emaGateway,ema,"call", "JSON/HTTP")
    Rel_D(AuthUI,emaGateway,"call", "JSON/HTTP")
    Rel_D(emaGateway,userAuth,"call", "JSON/HTTP")
    Rel_L(userAuth,emaGateway,"call", "JSON/HTTP")
    Rel_D(emaGateway,ema,"call", "JSON/HTTP")
}


Boundary(platformSystem, "Platform Context") {
    System_Ext(atlas, "Atlas", "网关管理")
    System_Ext(guard, "Guard", "登录和登出")
    System_Ext(oceanBase, "OceanBase", "用户权限管理")
    System_Ext(fort, "Fort", "网关管理")
    System_Ext(ant, "Ant", "数据点管理")
    System_Ext(hardcore, "Hardcore", "数据管理")

    Rel_D(ema,atlas,"call", "JSON/HTTP")
    Rel_D(ema,guard,"call", "JSON/HTTP")
    Rel_D(ema,oceanBase,"call", "JSON/HTTP")
    Rel_D(ema,fort,"call", "JSON/HTTP")
    Rel_D(ema,ant,"call", "JSON/HTTP")
    Rel_D(ema,hardcore,"call", "JSON/HTTP")
}

Boundary(compSystem, "Comp Context") {
    System_Ext(fork, "Fork", "消息推送服务")
    System_Ext(abtree, "Abtree", "点位关系管理")
    System_Ext(cuckoo, "Cuckoo", "调度系统")
    System_Ext(vee, "comp-data-quality", "数据质量控制")

    Rel_U(ema,fork,"call", "JSON/HTTP")
    Rel_U(ema,abtree,"call", "JSON/HTTP")
    Rel_U(cuckoo,ema,"call", "JSON/HTTP")
    ' Rel_U(ema,vee,"call", "JSON/HTTP")
}


Boundary(AI&BD, "AI&BD") {
    System_Ext(athena, "Athena", "算法服务")
    System_Ext(indie2, "Indie2", "计算服务")

    Rel_U(indie2,ema,"call", "JSON/HTTP")
    Rel_U(indie2,athena,"call", "JSON/HTTP")
}

Boundary(middleware, "middleware") {
    ContainerQueue(rabbitMq, "RabbitMq", "消息中间件")
    Rel_L(rabbitMq,ema,"call", "JSON/HTTP")
}


Boundary(thirdPartySystem, "Third-party Context") {
    System_Ext(gis, "高德地图", "用户获取地图信息")
    System_Ext(oss, "文件管理", "阿里文件存储系统")
    Rel_R(emaUI,gis,"call", "JSON/HTTP")
    Rel_R(userAuth,oss,"call", "JSON/HTTP")
}

Boundary(emaDatabase, "Database") {
    ContainerDb(emaForecast, "ema forecast", "pgsql", "ema 预测配置数据库")
    ContainerDb(emaDb, "ema", "pgsql", "ema 主数据库")
    ContainerDb(energymostDb, "Energymost Database", "sqlserver", "ema 预测配置数据库")
    ContainerDb(calendar, "Calendar", "日历数据库")
    ContainerDb(redis, "Redis", "ema 缓存数据库")
    Rel_D(ema,redis,"call", "JSON/HTTP")
    Rel_D(userAuth,redis,"call", "JSON/HTTP")
    Rel_D(ema,emaDb,"call", "JSON/HTTP")
    Rel_D(ema,calendar,"call", "JSON/HTTP")
    Rel_D(ema,emaForecast,"call", "JSON/HTTP")
    Rel_D(ema,energymostDb,"call", "JSON/HTTP")

}


Rel_D(customer,ema,"call", "JSON/HTTP")


Rel_D(userAuth,oceanBase,"call", "JSON/HTTP")
Rel_D(userAuth,hardcore,"call", "JSON/HTTP")
Rel_D(veeUi,vee,"call", "JSON/HTTP")



@enduml
