@startuml energy_hub_system
!include ../C4_Context.puml
!include ../C4_Container.puml

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()

title EcoStruxure Microgrid Advisor

Person(customer2, Users, "运营人员")
Person(customer1, Users, "配置工程师")
Person(customer4, Users, "现场工程师")
Person(customer3, Users, "客户")


System(ema, "ema", "ema system")


System_Ext(xiot, "emop", "Platform Context")

Container_Ext(abtree, "Abtree", "点位关系管理")

System_Ext(vee, "vee", "数据质量控制")


System_Ext(athena, "AI算法服务", "")
System_Ext(indie2, "数据计算", "")


Boundary(thirdPartySystem, "Third-party Context") {
    System_Ext(gis, "高德地图", "用户获取地图信息")
    System_Ext(oss, "文件管理", "阿里文件存储系统")
    System_Ext(geo, "和风天气", "和风天气")
}

' SystemQueue_Ext(rabbitMq, "RabbitMq", "消息中间件")
' Rel_R(rabbitMq,ema,"uses", "AMQP")

Rel_D(customer1,ema,"uses", "HTTPS")
Rel_D(customer2,ema,"uses", "HTTPS")
Rel_D(customer3,ema,"uses", "HTTPS")
Rel_D(customer4,ema,"uses", "HTTPS")


Rel_R(ema,gis,"uses", "HTTPS")
Rel_R(ema,geo,"uses", "HTTPS")
Rel_R(ema,oss,"uses", "HTTPS")

Rel_U(indie2,ema,"uses", "HTTP")
Rel_L(indie2,athena,"uses", "HTTP")
Rel_D(ema,abtree,"uses", "HTTP")
Rel_U(vee,ema,"uses", "HTTP")





Rel_D(ema,xiot,"uses", "HTTP")
Rel_D(customer1,xiot,"uses", "HTTPS")

@enduml
