@startuml energy_hub_system
!include ../C4_Context.puml

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()

title EcoStruxure Microgrid Advisor

Person(customer1, Users, "配置/现场/开发工程师")
Person(customer2, Users, "运营人员")
Person(customer3, Users, "客户")


System(ema, "ema", "ema system")


System_Ext(xiot, "emop", "Platform Context")

System_Ext(compSystem, "Comp Context", "Comp Context")


Boundary(AI&BD, "AI&BD") {
     System_Ext(athena, "Athena", "算法服务")
     System_Ext(indie2, "Indie2", "计算服务")
}


Boundary(thirdPartySystem, "Third-party Context") {
    System_Ext(gis, "高德地图", "用户获取地图信息")
    System_Ext(oss, "文件管理", "阿里文件存储系统")
    System_Ext(geo, "和风天气", "和风天气")
}

Rel_D(customer1,ema,"call", "JSON/HTTP")
Rel_D(customer2,ema,"call", "JSON/HTTP")
Rel_D(customer3,ema,"call", "JSON/HTTP")


Rel_R(ema,gis,"call", "JSON/HTTP")
Rel_R(ema,geo,"call", "JSON/HTTP")
Rel_R(ema,oss,"call", "JSON/HTTP")

Rel_U(indie2,ema,"call", "JSON/HTTP")
Rel_L(indie2,athena,"call", "JSON/HTTP")
Rel_D(ema,compSystem,"call", "JSON/HTTP")






Rel_D(ema,xiot,"call", "JSON/HTTP")

@enduml
